/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import Controller.Driver;
import static Controller.Driver.Attack;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class Target extends javax.swing.JInternalFrame {

    /**
     * Creates new form Target
     */
    public Target() {
        initComponents();
        rbSingleUsr.doClick();
        rbSinglePwd.doClick();
    }
    
    //Console consol = new Console();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        files = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        URL = new javax.swing.JTextField();
        usrName = new javax.swing.JLabel();
        usrTID = new javax.swing.JComboBox<>();
        ElementIDT = new javax.swing.JLabel();
        ElementID = new javax.swing.JLabel();
        usrID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSingleUsr = new javax.swing.JTextField();
        rbSingleUsr = new javax.swing.JRadioButton();
        rbTargetListUsr = new javax.swing.JRadioButton();
        txtTargetListUsr = new javax.swing.JTextField();
        btnFile1 = new javax.swing.JButton();
        btnFile2 = new javax.swing.JButton();
        txtTargetListPwd = new javax.swing.JTextField();
        txtSinglePwd = new javax.swing.JTextField();
        pwdID = new javax.swing.JTextField();
        pwdTID = new javax.swing.JComboBox<>();
        rbTargetListPwd = new javax.swing.JRadioButton();
        rbSinglePwd = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ElementID1 = new javax.swing.JLabel();
        ElementIDT1 = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        chAlert = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        btnID = new javax.swing.JTextField();
        btnTID = new javax.swing.JComboBox<>();
        ElementID4 = new javax.swing.JLabel();
        ElementIDT4 = new javax.swing.JLabel();
        pass2 = new javax.swing.JLabel();

        files.setDialogTitle("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(446, 600));
        setMinimumSize(new java.awt.Dimension(446, 100));
        setPreferredSize(new java.awt.Dimension(446, 649));

        URL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        URL.setToolTipText("");
        URL.setMaximumSize(new java.awt.Dimension(446, 600));
        URL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                URLFocusLost(evt);
            }
        });
        URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLActionPerformed(evt);
            }
        });

        usrName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        usrName.setText("User:");

        usrTID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Class Name", "Name", "XPath" }));
        usrTID.setMaximumSize(new java.awt.Dimension(80, 20));

        ElementIDT.setText("Element ID Type");

        ElementID.setText("Element ID");

        usrID.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Credential");

        txtSingleUsr.setToolTipText("");
        txtSingleUsr.setMaximumSize(new java.awt.Dimension(6, 20));

        rbSingleUsr.setText("Single Target");
        rbSingleUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSingleUsrActionPerformed(evt);
            }
        });

        rbTargetListUsr.setText("Target List");
        rbTargetListUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTargetListUsrActionPerformed(evt);
            }
        });

        txtTargetListUsr.setEditable(false);
        txtTargetListUsr.setToolTipText("");
        txtTargetListUsr.setMaximumSize(new java.awt.Dimension(6, 20));
        txtTargetListUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTargetListUsrMouseClicked(evt);
            }
        });
        txtTargetListUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargetListUsrActionPerformed(evt);
            }
        });

        btnFile1.setText("jButton1");
        btnFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile1ActionPerformed(evt);
            }
        });

        btnFile2.setText("jButton1");
        btnFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFile2ActionPerformed(evt);
            }
        });

        txtTargetListPwd.setEditable(false);
        txtTargetListPwd.setToolTipText("");
        txtTargetListPwd.setMaximumSize(new java.awt.Dimension(6, 20));
        txtTargetListPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTargetListPwdMouseClicked(evt);
            }
        });
        txtTargetListPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTargetListPwdActionPerformed(evt);
            }
        });

        txtSinglePwd.setToolTipText("");
        txtSinglePwd.setMaximumSize(new java.awt.Dimension(6, 20));

        pwdID.setMaximumSize(new java.awt.Dimension(6, 20));

        pwdTID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Class Name", "Name", "XPath" }));
        pwdTID.setMaximumSize(new java.awt.Dimension(80, 20));

        rbTargetListPwd.setText("Target List");
        rbTargetListPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTargetListPwdActionPerformed(evt);
            }
        });

        rbSinglePwd.setText("Single Target");
        rbSinglePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSinglePwdActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Credential");

        ElementID1.setText("Element ID");

        ElementIDT1.setText("Element ID Type");

        pass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pass.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("There are any alert if the login failed ?");

        chAlert.setText("Yes");

        btnLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnID.setMaximumSize(new java.awt.Dimension(6, 20));

        btnTID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Class Name", "Name", "XPath" }));
        btnTID.setMaximumSize(new java.awt.Dimension(80, 20));

        ElementID4.setText("Element ID");

        ElementIDT4.setText("Element ID Type");

        pass2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pass2.setText("Login button:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(URL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pass2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usrName)
                                    .addComponent(pass)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chAlert)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ElementIDT)
                                    .addComponent(ElementID)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usrID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usrTID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbSingleUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                            .addComponent(rbTargetListUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtTargetListUsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSingleUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ElementIDT1)
                                    .addComponent(ElementID1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pwdTID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 4, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(rbSinglePwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rbTargetListPwd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtTargetListPwd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtSinglePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ElementIDT4)
                                    .addComponent(ElementID4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(URL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(usrName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usrTID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElementIDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElementID)
                    .addComponent(usrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSingleUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSingleUsr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTargetListUsr)
                    .addComponent(txtTargetListUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdTID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElementIDT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElementID1)
                    .addComponent(pwdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSinglePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbSinglePwd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTargetListPwd)
                    .addComponent(txtTargetListPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(pass2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ElementIDT4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ElementID4)
                    .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chAlert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLActionPerformed

    private void rbSingleUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSingleUsrActionPerformed
        // TODO add your handling code here:
        if(rbTargetListUsr.isSelected()){
            rbTargetListUsr.setSelected(false);
            btnFile1.setEnabled(false);
        }
        txtTargetListUsr.setEnabled(false);
        txtSingleUsr.setEnabled(true);
    }//GEN-LAST:event_rbSingleUsrActionPerformed

    private void txtTargetListUsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTargetListUsrMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtTargetListUsrMouseClicked

    private void txtTargetListUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetListUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetListUsrActionPerformed

    private void btnFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile1ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt", "txt");
        files.setFileFilter(filtro);
        int a = files.showOpenDialog(this);
        if(a == JFileChooser.APPROVE_OPTION){
            File archivo = files.getSelectedFile();
            txtTargetListUsr.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnFile1ActionPerformed

    private void rbTargetListUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTargetListUsrActionPerformed
        // TODO add your handling code here:
        if(rbSingleUsr.isSelected()){
            rbSingleUsr.setSelected(false);
        }
        btnFile1.setEnabled(true);
        txtSingleUsr.setEnabled(false);
        txtTargetListUsr.setEnabled(true);
    }//GEN-LAST:event_rbTargetListUsrActionPerformed

    private void btnFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFile2ActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt", "txt");
        files.setFileFilter(filtro);
        int a = files.showOpenDialog(this);
        if(a == JFileChooser.APPROVE_OPTION){
            File archivo = files.getSelectedFile();
            txtTargetListPwd.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnFile2ActionPerformed

    private void txtTargetListPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTargetListPwdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTargetListPwdMouseClicked

    private void txtTargetListPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTargetListPwdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTargetListPwdActionPerformed

    private void rbTargetListPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTargetListPwdActionPerformed
        // TODO add your handling code here:
        if(rbSinglePwd.isSelected()){
            rbSinglePwd.setSelected(false);
        }
        btnFile2.setEnabled(true);
        txtSinglePwd.setEnabled(false);
        txtTargetListPwd.setEnabled(true);
    }//GEN-LAST:event_rbTargetListPwdActionPerformed

    private void rbSinglePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSinglePwdActionPerformed
        // TODO add your handling code here:
        if(rbTargetListPwd.isSelected()){
            rbTargetListPwd.setSelected(false);
            btnFile2.setEnabled(false);
        }
        txtTargetListPwd.setEnabled(false);
        txtSinglePwd.setEnabled(true);        
    }//GEN-LAST:event_rbSinglePwdActionPerformed

    private void URLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_URLFocusLost
        // TODO add your handling code here:
        this.setTitle(this.URL.getText());
    }//GEN-LAST:event_URLFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        //consol.setVisible(true);
        String url, tpusr, idusr, txtuser = "", tppass, idpass, txtpass = "", tplog, idlog;
        //consol.Write("[*] Starting Driver...");
        System.out.println("[*] Starting Driver...");
        URL rutaca = Target.class.getProtectionDomain().getCodeSource().getLocation();
        String ruta = rutaca.toString().substring(6, rutaca.toString().length()-4);
        System.out.println(ruta+"/"+"Drivers/chromedriver/chromedriver.exe");
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {}
        WebDriver driver = Driver.Start();
        if(driver == null){
            //consol.Write("[-] Error on Driver");
            System.out.println("[-] Error on Driver");
        }else{
            //consol.Write("[*] Driver Started...");
            System.out.println("[*] Driver Started...");
        }        
        url = URL.getText();
        Driver.login(driver,url);
        //consol.Write("[*] Accessing to URL "+url);
        //consol.Write("[*] Finding Elements...");
        System.out.println("[*] Accessing to URL "+url);
        System.out.println("[*] Finding Elements...");
        tpusr = usrTID.getSelectedItem().toString();
        idusr = usrID.getText();
        WebElement txtusr = Driver.Find(driver, tpusr, idusr);
        if(txtusr==null){
            //consol.Write("[*] Can't found the element "+tpusr+"=\""+idusr+"\"");
            System.out.println("[*] Can't found the element "+tpusr+"=\""+idusr+"\"");
        }else{
            //consol.Write("[*] Element found "+tpusr+"=\""+idusr+"\"");
            System.out.println("[*] Element found "+tpusr+"=\""+idusr+"\"");
        }
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {}
        tppass = pwdTID.getSelectedItem().toString();
        idpass = pwdID.getText();
        WebElement txtpwd = Driver.Find(driver, tppass, idpass);
        if(txtpwd==null){
            //consol.Write("[*] Can't found the element "+tppass+"=\""+idpass+"\"");
            System.out.println("[*] Can't found the element "+tppass+"=\""+idpass+"\"");
        }else{
            //consol.Write("[*] Element found "+tppass+"=\""+idpass+"\"");
            System.out.println("[*] Element found "+tppass+"=\""+idpass+"\"");
        }
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ex) {}
        tplog = btnTID.getSelectedItem().toString();
        idlog = btnID.getText();
        WebElement btnlog = Driver.Find(driver, tplog, idlog);
        if(btnlog==null){
            //consol.Write("[*] Can't found the element "+tplog+"=\""+idlog+"\"");
            System.out.println("[*] Can't found the element "+tplog+"=\""+idlog+"\"");
        }else{
            //consol.Write("[*] Element found "+tplog+"=\""+idlog+"\"");
            System.out.println("[*] Element found "+tplog+"=\""+idlog+"\"");
        }
        Boolean check = false ;
        Integer targetUsers =0,targetPwds = 0;
        if(chAlert.isSelected()){
            check = true;
        }
        
        if(rbSingleUsr.isSelected()){
            txtuser = txtSingleUsr.getText();
            targetUsers = 0;
        }
        
        if(rbTargetListUsr.isSelected()){
            txtuser = txtTargetListUsr.getText();
            targetUsers = 1;
        }
        
        if(rbSinglePwd.isSelected()){
            txtpass = txtSinglePwd.getText();
            targetPwds = 0;
        }
        
        if(rbTargetListPwd.isSelected()){
            txtpass = txtTargetListPwd.getText();
            targetPwds = 1;
        }
        
        try {
            Attack(driver, tpusr, idusr, tppass, idpass, tplog, idlog, txtuser, txtpass, check, targetUsers, targetPwds);
        }catch (InterruptedException ex) {
           Logger.getLogger(Target.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Target.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("\n[+] Finish");
        Driver.Stop();
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElementID;
    private javax.swing.JLabel ElementID1;
    private javax.swing.JLabel ElementID4;
    private javax.swing.JLabel ElementIDT;
    private javax.swing.JLabel ElementIDT1;
    private javax.swing.JLabel ElementIDT4;
    private javax.swing.JTextField URL;
    private javax.swing.JButton btnFile1;
    private javax.swing.JButton btnFile2;
    private javax.swing.JTextField btnID;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> btnTID;
    private javax.swing.JCheckBox chAlert;
    private javax.swing.JFileChooser files;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel pass2;
    private javax.swing.JTextField pwdID;
    private javax.swing.JComboBox<String> pwdTID;
    private javax.swing.JRadioButton rbSinglePwd;
    private javax.swing.JRadioButton rbSingleUsr;
    private javax.swing.JRadioButton rbTargetListPwd;
    private javax.swing.JRadioButton rbTargetListUsr;
    private javax.swing.JTextField txtSinglePwd;
    private javax.swing.JTextField txtSingleUsr;
    private javax.swing.JTextField txtTargetListPwd;
    private javax.swing.JTextField txtTargetListUsr;
    private javax.swing.JTextField usrID;
    private javax.swing.JLabel usrName;
    private javax.swing.JComboBox<String> usrTID;
    // End of variables declaration//GEN-END:variables
}
